import logging
import os

from dotenv import load_dotenv

load_dotenv()

IS_TEST = os.getenv("IS_TEST", "0") == "1"

EXIT_CODE_SKIPPED = 100

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))

REPO_DIR = os.path.join(PROJECT_DIR, "repos")
WIKI_DIR = os.path.join(PROJECT_DIR, "wikis")
INDEX_DIR = os.path.join(PROJECT_DIR, "indexes")

GITHUB_ACCESS_TOKEN = os.getenv("GITHUB_ACCESS_TOKEN", "")

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s|%(filename)s|%(levelname)s] %(message)s",
    datefmt="%m-%d %H:%M",
)
Logger = logging.getLogger("app")

MAX_EMBEDDING_TOKENS = 8191
MAX_INPUT_TOKENS = 8191

CONFIG = {
    "agent": {
        "prompt": os.path.join(PROJECT_DIR, "prompts", "agent_prompt2"),
    },
    "index_generation": {
        "model": "openai/gpt-4o",
        "prompt": os.path.join(PROJECT_DIR, "prompts", "index_prompt1"),
    },
    "page_generation": {
        "model": "openai/gpt-4.1",
        "temperature": 0.4,
        "top_p": 0.8,
        "prompt": os.path.join(PROJECT_DIR, "prompts", "page_prompt6"),
    },
    "structure_generation": {
        "model": "openai/gpt-4.1",
        "temperature": 0.4,
        "prompt": os.path.join(PROJECT_DIR, "prompts", "structure_prompt5"),
    },
    "embedder": {
        "model": "text-embedding-3-small",
        "dimensions": 1024,
        "chunk_size": 2048,
        "chunk_overlap": 256,
    },
    "tokenizer": {
        "model": "gpt-4o-mini",
    },
    "file_filters": {
        "code_extensions": [
            ".py",
            ".js",
            ".ts",
            ".java",
            ".cpp",
            ".c",
            ".go",
            ".rs",
            ".jsx",
            ".tsx",
            ".html",
            ".css",
            ".php",
            ".swift",
            ".cs",
            ".kt",
            ".sh",
        ],
        "doc_extensions": [
            ".txt",
            ".md",
            ".json",
            ".yaml",
            ".yml",
            ".xml",
            ".toml",
            ".in",
            ".cursorrules",
        ],
        "excluded_dirs": [
            "./.venv/",
            "./venv/",
            "./env/",
            "./virtualenv/",
            "./node_modules/",
            "./bower_components/",
            "./jspm_packages/",
            "./.git/",
            "./.svn/",
            "./.hg/",
            "./.bzr/",
            "./__pycache__/",
            "./.pytest_cache/",
            "./.mypy_cache/",
            "./.ruff_cache/",
            "./.coverage/",
            "./dist/",
            "./build/",
            "./out/",
            "./target/",
            "./bin/",
            "./obj/",
            "./docs/",
            "./_docs/",
            "./site-docs/",
            "./_site/",
            "./.idea/",
            "./.vscode/",
            "./.vs/",
            "./.eclipse/",
            "./.settings/",
            "./logs/",
            "./log/",
            "./tmp/",
            "./temp/",
        ],
        "excluded_files": [
            "package-lock.json",
            "yarn.lock",
            "pnpm-lock.yaml",
            "npm-shrinkwrap.json",
            "poetry.lock",
            "Pipfile.lock",
            "requirements.txt.lock",
            "Cargo.lock",
            "composer.lock",
            ".lock",
            ".DS_Store",
            "Thumbs.db",
            "desktop.ini",
            "*.lnk",
            ".env",
            ".env.*",
            "*.env",
            "*.cfg",
            "*.ini",
            ".flaskenv",
            ".gitignore",
            ".gitattributes",
            ".gitmodules",
            ".github",
            ".gitlab-ci.yml",
            ".prettierrc",
            ".eslintrc",
            ".eslintignore",
            ".stylelintrc",
            ".editorconfig",
            ".jshintrc",
            ".pylintrc",
            ".flake8",
            "mypy.ini",
            "pyproject.toml",
            "tsconfig.json",
            "webpack.config.js",
            "babel.config.js",
            "rollup.config.js",
            "jest.config.js",
            "karma.conf.js",
            "vite.config.js",
            "next.config.js",
            "*.min.js",
            "*.min.css",
            "*.bundle.js",
            "*.bundle.css",
            "*.map",
            "*.gz",
            "*.zip",
            "*.tar",
            "*.tgz",
            "*.rar",
            "*.pyc",
            "*.pyo",
            "*.pyd",
            "*.so",
            "*.dll",
            "*.class",
            "*.exe",
            "*.o",
            "*.a",
            "*.jpg",
            "*.jpeg",
            "*.png",
            "*.gif",
            "*.ico",
            "*.svg",
            "*.webp",
            "*.mp3",
            "*.mp4",
            "*.wav",
            "*.avi",
            "*.mov",
            "*.webm",
            "*.csv",
            "*.tsv",
            "*.xls",
            "*.xlsx",
            "*.db",
            "*.sqlite",
            "*.sqlite3",
            "*.pdf",
            "*.docx",
            "*.pptx",
            "*.css",
            "*.ttf",
            "*.otf",
            "*.woff",
            "*.woff2",
        ],
    },
}
